export const mock = { resa :[
    {
        id:1,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:2,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:3,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:4,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    } ,
    {
        id:5,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:6,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    } 
    ,  {
        id:7,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:8,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    } ,
    {
        id:9,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:10,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    } ,
    {
        id:11,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:12,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:13,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:14,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:15,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Loraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:16,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours",
        prenom:"Milan",
        street_adress:"24 rte des mottes gachins",
        postal_code:"31400",
        city:"Aix",
        country:"France",
        email:"mail@mail.com",
        telephone:"090807428",
        montant_regle:"79.28",
        reste_percevoir:"300.23",
        taxe_sejour:"39.40",
        nb_adultes:4,
        nb_enfants:12,
        nb_bebe:1,
        nb_animaux:0,
        menage:true,
        serviettes:false,
        chauffage:false,
        prec_resa:"Lorem Ipsum dolor fkajnf zfz,fz zfzf",
        prec_animaux:"Berger Australien",
        prev_enfant:"10ans garcon"

    },
    {
        id:17,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:18,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:19,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:20,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:21,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:22,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:23,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:24,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:25,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:26,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:27,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:28,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:29,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:30,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:31,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:32,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    },
    {
        id:33,
        date_debut:"27-01-2022",
        date_fin: "02-02-2022",
        nom:"Rougemont",
        state : "Expirée"
    },
    {
        id:34,
        date_debut:"29-06-2022",
        date_fin: "07-07-2022",
        nom:"Varela-Mujica",
        state : "En cours"
    }
    // more records...
]}